package start;

public enum ShapePoint {
	POINT_LINE_X1Y1,
	POINT_LINE_X2Y2,
	POINT_LINE_CENTER,
	POINT_RECTANGLE_UPPER_LEFT, 
	POINT_RECTANGLE_UPPER_RIGHT, 
	POINT_RECTANGLE_LOWER_LEFT, 
	POINT_RECTANLGE_LOWER_RIGHT, 
	POINT_RECTANLGE_CENTER, 
	POINT_CIRCLE_RADIUS,
	POINT_CIRCLE_CENTER,
	POINT_NONE 
}
